# chan theme configuration

# site setting
rss: /atom.xml
favicon: /favicon.png

# style setting
monochrome: true

# view setting
avatar: https://avatars3.githubusercontent.com/u/868552?v=4&s=460
avatarLink: /2017/09/04/About
maxContentWidth: 1000px # set the main content column's max-width property. keep it blank to unlimited the width
copyright: # the copyright text in the footer, could be richtext

# sidebar navigator structure
# It's a list with item that is also list.
# The item of first level list means a group of links,
# and the item of the second level list means exactly a link.
# A link item is an object whit two properties: 'name' for displaying and 'link' for redirecting.
# A link starts with http/https would be rendered as a tag with 'target="_blank"' .
# There are also some special link items representing in string: 'categories', 'tags' and 'archives'
nav:
  -
    - tags       # display a collapsible tag list
    - archives   # display a collapsible archive list
  -
    -
      name: Homepage
      url: '/'
    -
      name: By Year
      url: /archives
    -
      name: Functional Programming Techniques in Python
      url: /2019/03/01/Functional-Programming-Techniques-In-Python-Series/
  -
    -
      name: About
      url: /2017/09/04/About/
    -
      name: CV
      url: https://github.com/mpkocher/cv/blob/master/academic/cv.pdf
    -
      name: Github
      url: https://github.com/mpkocher
    -
      name: Gists
      url: https://gist.github.com/mpkocher
    - 
      name: LinkedIn
      url: https://www.linkedin.com/in/michael-kocher-b4bba5122/   
    -
      name: Twitter
      url: https://twitter.com/ElevenPhonons
    -
      name: Now
      url: /2017/09/04/Now
    -
      name: RSS
      url: /atom.xml

# duoshuo shortname
# refer to http://duoshuo.com
# If you use disqus then you should set disqus_shortname in your site config and disable duoshuo here.
# You also need to set 'comments' to true in the front-matter
#duoshuo: sprabbit

# jiathis share id
# refer to http://jiathis.com
#jiathis: 1589291

# open graph
twitter: https://twitter.com/ElevenPhonons
google_plus:
fb_admins:
fb_app_id:

# analytics ids
google_analytics: UA-141397134-1
baidu_statistics:

# default creative commons
# There are 6 kinds of combination and place 'none' to disable.
# - by
# - by-sa
# - by-nd
# - by-nc
# - by-nc-sa
# - by-nc-nd
# - none
# This setting could be overwritten in the front matter of a post.
# More details in https://creativecommons.org
cc: by-sa

# FancyBox / PhotoSwipe
# Although it is called fancybox, we use PhotoSwipe instead.
# Check http://photoswipe.com
fancybox: true    # enable fancybox/photoswipe rendering
# photoswipe: true  # the same
